version: '3.4'

services:
  # property_api:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile.dev
  #   environment:
  #     NODE_ENV: development
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - .:/usr/app
  #     - /usr/app/node_modules
  property_db:
    container_name: property_db
    image: mysql
    volumes:
      - db:/var/lib/mysql
    ports: 
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: "${TYPEORM_PASSWORD}"
      MYSQL_DATABASE: "${TYPEORM_DATABASE}"
volumes: 
  db: