version: '3.4'

services:
  property_api:
    build: .
    container_name: "property_api"
    command: npm run start:dev
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
    links:
      - property_db
    depends_on:
      - property_db
    environment:
      DB_HOST: ${DATABASE_HOST}
      DB_USER: ${DATABASE_USER}
      DB_PASS: ${DATABASE_PASSWORD}
      DB_NAME: ${DATABASE_NAME}
  property_db:
    container_name: property_db
    image: mysql
    volumes:
      - db:/var/lib/mysql
    ports: 
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: "${DATABASE_PASSWORD}"
      MYSQL_DATABASE: "${DATABASE_NAME}"
volumes: 
  db:
networks:
  overlay: